version: '3.4'
services:
  db:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_DB: dogfight
      POSTGRES_USER: dogfight_user
      POSTGRES_PASSWORD: dogfight_pass
    volumes:
      - ${PWD}/data/postgres:/var/lib/postgresql/data
      - ${PWD}/schema.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 4232:5432
